# Generated by Django 5.1.3 on 2024-11-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('customer', 'Customer')], max_length=8, null=True),
        ),
    ]
