# Generated by Django 5.1.3 on 2024-11-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0005_offer_min_delivery_time_offerdetail_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=-1),
        ),
    ]
