# Generated by Django 5.1.3 on 2024-11-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0006_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
    ]
